[package]
name = "scion"
version = "0.1.0"
authors = ["grzi <jeremy.thulliez@gmail.com>"]
edition = "2018"

[dependencies]
legion = "0.4.0"

# window & rendering
miniquad = "0.3.0-alpha.26"

# accurate time sleeping
spin_sleep = "1.0.0"

# serialization
serde = "1.0.124"
toml = "0.5.8"

# logging
log = { version = "0.4.14", features = ["serde"] }
fern = { version = "0.6.0", features = ["colored"] }