name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -Cdebuginfo=0
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v2

      - name: install linux deps
        run: |
          sudo apt update
          sudo apt install gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
        if: contains(matrix.os, 'ubuntu')

      - name: install ${{ matrix.toolchain }} toolchain
        id: install_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - uses: seanmiddleditch/gha-setup-ninja@master
        if: matrix.os == 'windows-latest'

      - run: rustup component add rustfmt
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'

      - run: cargo +nightly fmt --all -- --check
        if: matrix.toolchain == 'nightly' && matrix.os == 'ubuntu-latest'

      - run: rustup component add clippy
        if: matrix.toolchain == 'nightly'

      - run: cargo test --workspace --all-features --all-targets